import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import SessionProviderWrapper from "@/provider/session.provider";
import { ToastContainer } from "react-toastify";
import ReactQueryProvider from "@/provider/reactQuery.provider";
import "./globals.css";
import "../style/slate.css";
import "react-quill-new/dist/quill.snow.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SessionProviderWrapper>
          <ToastContainer />
          <ReactQueryProvider>{children}</ReactQueryProvider>
        </SessionProviderWrapper>
      </body>
    </html>
  );
}
